### ISSUE TITLE
How do we replace the bad words?

### ISSUE THREAD

**Issue by jasonlaw** [TylerSustare/dart_bad_words#1]
We found the bad words, then how do we replace it the bad words to obscure text, e.g. this is bad words => this is *********?

**Comment by TylerSustare** [comment]
Hi @jasonlaw thank you for asking about this. I just added a `clean` method to the class that will do just as you suggested and turn the bad words found into an asterisk string of the same length. If you'd like to add another suggestion I'm open to it!
