### ISSUE TITLE
Clean will not work for bad word with space

### ISSUE THREAD

**Issue by jasonlaw** [TylerSustare/dart_bad_words#3]
Thanks for making the clean method.
However, the clean will not work for bad word like "carpet muncher".

**Comment by TylerSustare** [comment]
🤦  You're so right, thank you. Adding to the project to work on soon.

**Comment by TylerSustare** [comment]
Just checking back in on this. It's not forgotten 🙂. It's taking me longer than I had expected to get the regex right for the words with spaces. I have that pice down and now I'm figuring out the best way to handle special characters in the bad words list without modifying the regex pattern. **sh!+** for example will modify the regex we're searching for. 

I'm exploring wether that's rewriting the `isProfane` to use regex as well and modifying the list or a different solution.
