### ISSUE TITLE
Unnecessary dependency on Flutter

### ISSUE THREAD

**Issue by benbarbersmith** [TylerSustare/dart_bad_words#4]
This is a very handy Dart library, but it has an unnecessary dependency on Flutter. This prevents the library being used with other Dart programs (such as CLI applications, AngularDart applications, code run through `dart2js`, etc.).

The only part of the library that uses any Flutter code is here:

https://github.com/TylerSustare/dart_bad_words/blob/7a49f38b62de40128e2fd243268067105bd19ce4/bad_words/test/bad_words_test.dart#L1 

Because no Flutter features are used, `package:test/test.dart` is a drop-in replacement for `package:flutter_test/flutter_test.dart`.

I propose removing the dependency on Flutter so this library can be used with any Dart project.

PR to follow shortly.

**Comment by TylerSustare** [comment]
Successfully updated to https://pub.dev/packages/bad_words

Thanks again @benbarbersmith much appreciated!
